export type TwoLineElement = {
    noradNr: number,
    classification: string,
    internationalDesignator: string,
    epochYear: number,
    epochDayOfYear: number,
    firstDerivativeMeanMotion: number,
    secondDerivativeMeanMotion: number,
    dragTerm: number,
    ephemerisType: number,
    setNumber: number,
    catalogNumber: number,
    inclination: number,
    rightAscension: number,
    eccentricity: number,
    argumentOfPerigee: number,
    meanAnomaly: number,
    meanMotion: number,
    revolution: number,
}
