"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DAY_OF_WEEK_SATURDAY = exports.DAY_OF_WEEK_FRIDAY = exports.DAY_OF_WEEK_THURSDAY = exports.DAY_OF_WEEK_WEDNESDAY = exports.DAY_OF_WEEK_TUESDAY = exports.DAY_OF_WEEK_MONDAY = exports.DAY_OF_WEEK_SUNDAY = void 0;
exports.DAY_OF_WEEK_SUNDAY = 0;
exports.DAY_OF_WEEK_MONDAY = 1;
exports.DAY_OF_WEEK_TUESDAY = 2;
exports.DAY_OF_WEEK_WEDNESDAY = 3;
exports.DAY_OF_WEEK_THURSDAY = 4;
exports.DAY_OF_WEEK_FRIDAY = 5;
exports.DAY_OF_WEEK_SATURDAY = 6;
