export declare function getMeanElongation(T: number): number;
export declare function getMeanAnomaly(T: number): number;
export declare function getArgumentOfLatitude(T: number): number;
export declare function getMeanLongitude(T: number): number;
export declare function getEquatorialHorizontalParallax(T: number): number;
export declare function getDistanceToEarth(T: number): number;
export declare function getLongitude(T: number): number;
export declare function getApparentLongitude(T: number): number;
export declare function getLatitude(T: number): number;
