# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check code quality

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: 'Setup cache for node_modules'
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: 'Install project'
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

#      - name: 'Check code style'
#        run: yarn lint

      - name: 'Run unit tests'
        run: yarn test

      - name: 'Build project'
        run: yarn build
